package com.mentormatching.modules.media.infrastructure.cloudinary;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.time.Instant;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.TreeMap;
import java.util.UUID;

import org.springframework.stereotype.Component;

import com.mentormatching.modules.media.application.dto.ConfirmMediaUploadCommand;
import com.mentormatching.modules.media.application.dto.CreateMediaUploadCommand;
import com.mentormatching.modules.media.application.dto.MediaUploadIntent;
import com.mentormatching.modules.media.application.port.out.MediaStoragePort;
import com.mentormatching.modules.media.domain.MediaAsset;
import com.mentormatching.modules.media.domain.MediaProvider;
import com.mentormatching.modules.media.domain.MediaResourceType;
import com.mentormatching.shared.exception.InvalidDataException;

@Component
public class CloudinaryMediaStorageAdapter implements MediaStoragePort {

    private static final String CLOUDINARY_UPLOAD_URL_FORMAT = "https://api.cloudinary.com/v1_1/%s/%s/upload";

    private final CloudinaryProperties cloudinaryProperties;

    public CloudinaryMediaStorageAdapter(CloudinaryProperties cloudinaryProperties) {
        this.cloudinaryProperties = cloudinaryProperties;
    }

    @Override
    public MediaProvider provider() {
        return MediaProvider.CLOUDINARY;
    }

    /**
     * Creates the provider object key for a new Cloudinary upload.
     * <p>
     * In Cloudinary, this value is used as the {@code public_id}. The key is generated by the backend
     * instead of trusting the original filename so uploads are collision-safe, predictable for cleanup,
     * and do not expose user-provided filenames.
     * <p>
     * Example result:
     * {@code mentor-matching/users/15/avatar/8f37a6dbe9f84e4490aef832da19c222}
     */
    @Override
    public String createObjectKey(CreateMediaUploadCommand command) {
        String userSegment = "users/" + command.uploadedByUserId();
        String purposeSegment = command.purpose().name().toLowerCase(Locale.ROOT);
        String uniqueSegment = UUID.randomUUID().toString().replace("-", "");

        return String.join("/", cloudinaryProperties.uploadFolder(), userSegment, purposeSegment, uniqueSegment);
    }

    @Override
    public MediaUploadIntent createUploadIntent(MediaAsset mediaAsset) {
        validateConfigured();

        String resourceType = toCloudinaryResourceType(mediaAsset.getResourceType());
        String uploadUrl = CLOUDINARY_UPLOAD_URL_FORMAT.formatted(cloudinaryProperties.cloudName(), resourceType);
        String timestamp = String.valueOf(Instant.now().getEpochSecond());

        Map<String, String> signedParams = new TreeMap<>();
        signedParams.put("public_id", mediaAsset.getObjectKey());
        signedParams.put("timestamp", timestamp);

        Map<String, String> formFields = new LinkedHashMap<>();
        formFields.put("api_key", cloudinaryProperties.apiKey());
        formFields.put("public_id", mediaAsset.getObjectKey());
        formFields.put("timestamp", timestamp);
        formFields.put("signature", sign(signedParams));

        return new MediaUploadIntent(mediaAsset.getId(), provider().name(), uploadUrl, mediaAsset.getObjectKey(),
                formFields);
    }

    @Override
    public void verifyUpload(MediaAsset mediaAsset, ConfirmMediaUploadCommand command) {
        validateConfigured();

        if (!mediaAsset.getObjectKey().equals(command.objectKey())) {
            throw new InvalidDataException("Cloudinary public id does not match upload intent");
        }
        if (command.providerAssetId() == null || command.providerAssetId().isBlank()) {
            throw new InvalidDataException("Cloudinary asset id is required");
        }
        if (command.deliveryUrl() == null || command.deliveryUrl().isBlank()) {
            throw new InvalidDataException("Cloudinary secure url is required");
        }
        if (!command.deliveryUrl().startsWith("https://res.cloudinary.com/" + cloudinaryProperties.cloudName() + "/")) {
            throw new InvalidDataException("Cloudinary secure url does not match configured cloud name");
        }
        if (command.fileSizeBytes() != null && command.fileSizeBytes() < 0) {
            throw new InvalidDataException("Cloudinary file size must not be negative");
        }
        if (command.width() != null && command.width() < 0) {
            throw new InvalidDataException("Cloudinary width must not be negative");
        }
        if (command.height() != null && command.height() < 0) {
            throw new InvalidDataException("Cloudinary height must not be negative");
        }
    }

    @Override
    public void delete(MediaAsset mediaAsset) {
        throw new UnsupportedOperationException("Cloudinary media deletion is not implemented yet");
    }

    private void validateConfigured() {
        if (cloudinaryProperties.cloudName().isBlank()) {
            throw new InvalidDataException("Cloudinary cloud name is required");
        }
        if (cloudinaryProperties.apiKey().isBlank()) {
            throw new InvalidDataException("Cloudinary api key is required");
        }
        if (cloudinaryProperties.apiSecret().isBlank()) {
            throw new InvalidDataException("Cloudinary api secret is required");
        }
    }

    private String sign(Map<String, String> params) {
        String payload = params.entrySet().stream()
                .map(entry -> entry.getKey() + "=" + entry.getValue())
                .reduce((left, right) -> left + "&" + right)
                .orElse("") + cloudinaryProperties.apiSecret();

        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-1");
            byte[] hash = digest.digest(payload.getBytes(StandardCharsets.UTF_8));
            StringBuilder signature = new StringBuilder(hash.length * 2);
            for (byte value : hash) {
                signature.append(String.format("%02x", value));
            }
            return signature.toString();
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException("SHA-1 algorithm is not available", e);
        }
    }

    private String toCloudinaryResourceType(MediaResourceType resourceType) {
        return switch (resourceType) {
            case IMAGE -> "image";
            case VIDEO -> "video";
            case RAW -> "raw";
        };
    }
}
