spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:mentor_matching_test;MODE=MySQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  flyway:
    enabled: false

springdoc:
  api-docs:
    enabled: ${SPRINGDOC_API_DOCS_ENABLED_TEST:true}

app:
  swagger:
    description: ${APP_SWAGGER_DESCRIPTION_TEST:API docs for test environment}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT_TEST:INFO}
    com.mentormatching: ${LOGGING_LEVEL_APP_TEST:DEBUG}
