spring:
  config:
    activate:
      on-profile: prod
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED_PROD:true}
  jpa:
    hibernate:
      ddl-auto: validate

springdoc:
  api-docs:
    enabled: ${SPRINGDOC_API_DOCS_ENABLED_PROD:true}
  swagger-ui:
    enabled: ${SPRINGDOC_SWAGGER_UI_ENABLED_PROD:false}

app:
  swagger:
    description: ${APP_SWAGGER_DESCRIPTION_PROD:API docs for production environment}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT_PROD:WARN}
    com.mentormatching: ${LOGGING_LEVEL_APP_PROD:INFO}
